### ISSUE TITLE
タスク管理/最低限/タスクの追加

### ISSUE THREAD

**Issue by aki3104** [aki3104/sabotask#13]
# ゴール
- タスクの追加できるようになる

# To do

## Rails
- [ ] Taskモデルの作成
- [ ] tasks#newアクションの実装

## Vue
- [ ] task_createコンポーネントを作成
- [ ] templateを作成（vuetify使用）

**Comment by terufumi1122** [comment]
>  Task追加モデルの作成

-> Taskモデルの作成　の方が良いかと思います^^

**Comment by aki3104** [comment]
> -> Taskモデルの作成　の方が良いかと思います^^

ちなみに理由って聞いても良いでしょうか？
超根本的な質問ですが
railsのController内でCRUDメソッドを追加するようなイメージだったので「Task追加モデル作成」まずかったですかね？

**Comment by terufumi1122** [comment]
> ちなみに理由って聞いても良いでしょうか？
-> 僕も大した知識ではありませんが、**モデル**というと、`User`とか`Task`とか、インスタンスを作成するためのテンプレのことを指すためです。

なので、`Task`モデルから出来た`tasks`インスタンスの`create`メソッドを作成する
という意味で、`tasks#create`という記載になります。
※`Task`から大量の`tasks`が出来るから複数形、ですね^^

解釈間違ってたらすみませんー！

**Comment by rikuro-aub** [comment]
> Taskモデルの作成

->Taskモデルの作成だけでなく、作成するカラム名も明示して記載した方が良いかなと思いました!
ex) title, contentなど

> tasks#addアクションの実装

->新規作成のアクションは`tasks#new`か`tasks#create`を使うイメージなのですが、`tasks#add`の`add`アクションにした理由って何かありますか?
あおっている意図はまったくなくて、純粋な疑問で...

その他で、アクションに対するルーティングの設定の記載をした方が良いかなと思いました!
ex1) index, new, create, update, destroyの基本的なアクションだけを使用するならば、どこかしらのissueに`tasksのresourcesをroutesに設定する`とか
ex2) 何か特別なアクションを設定するならば、`POSTメソッドでxxxアクションをroutesに設定する`とか
