### ISSUE TITLE
herokuに本番環境デプロイ出来る状態になっている

### ISSUE THREAD

**Issue by terufumi1122** [aki3104/sabotask#9]
# ゴール
herokuに本番環境デプロイが出来ている

# To do
- [x] `heroku config`の設定が完了している
- [x] 手動デプロイが成功する
- [x] GitHubとherokuが連携しており、自動デプロイ出来ている

## 参考記事
https://qiita.com/murakami-mm/items/9587e21fc0ed57c803d0
より、以下抜粋。
## 設定すべき環境変数
```
$ heroku config
=== <アプリの名前> Config Vars
CLEARDB_DATABASE_URL: mysql://<ユーザー名>:<パスワード>@<ホスト名>/<データベース名>?reconnect=true
```
環境変数の設定
上記コマンドで表示されたそれぞれの値を変数に設定する。

```
$ heroku config:add DB_NAME='<データベース名>'
$ heroku config:add DB_USERNAME='<ユーザー名>'
$ heroku config:add DB_PASSWORD='<パスワード>'
$ heroku config:add DB_HOSTNAME='<ホスト名>'
$ heroku config:add DB_PORT='3306'
$ heroku config:add DATABASE_URL='mysql2://<ユーザー名>:<パスワード>@<ホスト名>/<データベース名>?reconnect=true'
```

**Comment by rikuro-aub** [comment]
> heroku configの設定が完了している

->現時点でわかっているものだけでも、どの環境変数を設定するのか記載しておいた方が良いかなと思いました!
指摘しておきながら、何の環境変数が必要なのかわかっていないのですが...

**Comment by terufumi1122** [comment]
@rikuro-aub 
ご指摘ありがとうございます！
参考にしたQiitaの記事URLも含め追記しておきました！
